#!/usr/bin/env bash
# PR-raiser role — deterministic, no LLM.
# Usage: bash AGENTS/pr-riser.sh <phase-key> <branch-name> <pr-title>
# Creates phase branch, commits all changes, pushes, opens PR into main.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p build-logs
LOG="build-logs/pr.log"

PHASE_KEY="${1:?phase key required}"
BRANCH="${2:?branch required}"
TITLE="${3:?title required}"

echo "===== PR $PHASE_KEY → $BRANCH $(date '+%F %T') =====" | tee -a "$LOG"

# 1. Ensure on main with latest
git checkout main >> "$LOG" 2>&1 || { echo "❌ checkout main failed" | tee -a "$LOG"; exit 1; }
git pull origin main >> "$LOG" 2>&1 || true

# 2. Create/switch to phase branch (reuse if exists from a retry)
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git checkout "$BRANCH" >> "$LOG" 2>&1
else
  git checkout -b "$BRANCH" >> "$LOG" 2>&1
fi

# 3. Commit everything (builder may have already committed; catch stragglers)
if [ -n "$(git status --porcelain)" ]; then
  git add -A
  git commit -m "$TITLE" >> "$LOG" 2>&1 || true
fi

# 4. Push and open PR
git push -u origin "$BRANCH" >> "$LOG" 2>&1 || { echo "❌ push failed" | tee -a "$LOG"; exit 1; }
BODY="Auto-generated by the Able orchestrator.

Phase: $PHASE_KEY
Spec + gates: see ORCHESTRATOR.md section 4.

Built by the multi-agent graph (researcher glm-5.2 → builder deepseek-v4-pro →
verifier gates → pr-raiser). Verify: \`npm run verify\` + browser tests green."

if gh pr view "$BRANCH" --json number -q .number > /dev/null 2>&1; then
  echo "ℹ PR already exists for $BRANCH — skipping create" | tee -a "$LOG"
else
  gh pr create --base main --head "$BRANCH" --title "$TITLE" --body "$BODY" >> "$LOG" 2>&1 \
    && echo "✅ PR created for $BRANCH" | tee -a "$LOG" \
    || echo "⚠ PR create failed (maybe no diff vs main) — check $LOG" | tee -a "$LOG"
fi

# 5. Back to main for the next phase
git checkout main >> "$LOG" 2>&1
echo "✅ PR $PHASE_KEY done $(date '+%F %T')" | tee -a "$LOG"
exit 0
